# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: install
install:
	npm ci

.PHONY: lint
lint:
	npm run lint

.PHONY: build
build:
	npm run build:production

.PHONY: unit-test
unit-test:
	if [ ! -d "test-output" ]; then \
		mkdir test-output; \
	fi
	npm test
